// ASTROLOGERS DATA
export const ASTROLOGERS = [
  {
    id: "1",
    name: "Pandit Rajesh Sharma",
    rating: 4.9,
    experience: 15,
    pricePerMin: 25,
    isOnline: true,
    languages: ["Hindi", "English"],
    specialties: ["Career", "Marriage"],
    avatar: "👤",
  },
  {
    id: "2",
    name: "Dr. Meera Nair",
    rating: 4.8,
    experience: 12,
    pricePerMin: 30,
    isOnline: true,
    languages: ["Malayalam", "English"],
    specialties: ["Health", "Business"],
    avatar: "👩",
  },
  {
    id: "3",
    name: "Acharya Vikram",
    rating: 4.7,
    experience: 20,
    pricePerMin: 40,
    isOnline: false,
    languages: ["Hindi", "Sanskrit"],
    specialties: ["Vedic", "Remedies"],
    avatar: "👨‍🏫",
  },
  {
    id: "4",
    name: "Jyotishi Priya Devi",
    rating: 4.6,
    experience: 10,
    pricePerMin: 20,
    isOnline: true,
    languages: ["Tamil", "English"],
    specialties: ["Love", "Family"],
    avatar: "✨",
  },
  {
    id: "5",
    name: "Master Suresh Kumar",
    rating: 4.5,
    experience: 8,
    pricePerMin: 15,
    isOnline: true,
    languages: ["Hindi", "Marathi", "English"],
    specialties: ["Numerology", "Career"],
    avatar: "🔮",
  },
  {
    id: "6",
    name: "Swami Ananda",
    rating: 4.9,
    experience: 25,
    pricePerMin: 50,
    isOnline: false,
    languages: ["Hindi", "Sanskrit", "English"],
    specialties: ["Spiritual", "Life Path"],
    avatar: "🙏",
  },
];

// PRAYERS DATA
export const PRAYERS_DATA = {
  muslim: [
    {
      id: "m1",
      religion: "muslim",
      title: "Fajr Prayer",
      time: "5:00 AM",
      isLive: true,
      viewers: 1240,
    },
    {
      id: "m2",
      religion: "muslim",
      title: "Dhuhr Prayer",
      time: "12:30 PM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "m3",
      religion: "muslim",
      title: "Asr Prayer",
      time: "3:45 PM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "m4",
      religion: "muslim",
      title: "Maghrib Prayer",
      time: "6:30 PM",
      isLive: true,
      viewers: 890,
    },
    {
      id: "m5",
      religion: "muslim",
      title: "Isha Prayer",
      time: "8:00 PM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "m6",
      religion: "muslim",
      title: "Quran Recitation",
      time: "Live Now",
      isLive: true,
      viewers: 3200,
    },
  ],
  hindu: [
    {
      id: "h1",
      religion: "hindu",
      title: "Morning Aarti",
      time: "6:00 AM",
      isLive: true,
      viewers: 2100,
    },
    {
      id: "h2",
      religion: "hindu",
      title: "Shiva Puja",
      time: "7:00 AM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "h3",
      religion: "hindu",
      title: "Ganesh Aarti",
      time: "12:00 PM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "h4",
      religion: "hindu",
      title: "Evening Bhajan",
      time: "6:00 PM",
      isLive: true,
      viewers: 1500,
    },
    {
      id: "h5",
      religion: "hindu",
      title: "Hanuman Chalisa",
      time: "Live Now",
      isLive: true,
      viewers: 4200,
    },
  ],
  christian: [
    {
      id: "c1",
      religion: "christian",
      title: "Sunday Mass",
      time: "8:00 AM",
      isLive: true,
      viewers: 1800,
    },
    {
      id: "c2",
      religion: "christian",
      title: "Bible Study",
      time: "10:00 AM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "c3",
      religion: "christian",
      title: "Evening Prayer",
      time: "6:00 PM",
      isLive: true,
      viewers: 950,
    },
    {
      id: "c4",
      religion: "christian",
      title: "Gospel Choir",
      time: "7:00 PM",
      isLive: false,
      viewers: 0,
    },
    {
      id: "c5",
      religion: "christian",
      title: "Youth Fellowship",
      time: "Live Now",
      isLive: true,
      viewers: 620,
    },
  ],
};

// EDUCATION DATA
export const EDUCATION_DATA = {
  muslim: [
    {
      id: "me1",
      religion: "muslim",
      title: "Quran Classes",
      instructor: "Moulavi Ibrahim",
      level: "Beginner",
      students: 1200,
      price: "Free",
      icon: "📖",
      meetLink: "https://meet.google.com/abc-defg-hij",
    },
    {
      id: "me2",
      religion: "muslim",
      title: "Arabic Language",
      instructor: "Prof. Rashid",
      level: "Intermediate",
      students: 800,
      price: "₹299/mo",
      icon: "🗣️",
    },
    {
      id: "me3",
      religion: "muslim",
      title: "Islamic History",
      instructor: "Dr. Fazil",
      level: "All levels",
      students: 2400,
      price: "Free",
      icon: "📚",
    },
    {
      id: "me4",
      religion: "muslim",
      title: "Fiqh Studies",
      instructor: "Moulavi Hamza",
      level: "Advanced",
      students: 560,
      price: "₹199/mo",
      icon: "⚖️",
    },
  ],
  hindu: [
    {
      id: "he1",
      religion: "hindu",
      title: "Vedic Astrology",
      instructor: "Pandit Suresh",
      level: "Beginner",
      students: 3400,
      price: "₹499/mo",
      icon: "🌟",
      meetLink: "https://meet.google.com/xyz-pdqk-rst",
    },
    {
      id: "he2",
      religion: "hindu",
      title: "Sanskrit Classes",
      instructor: "Dr. Sharma",
      level: "All levels",
      students: 1100,
      price: "Free",
      icon: "📝",
    },
    {
      id: "he3",
      religion: "hindu",
      title: "Yoga & Meditation",
      instructor: "Guru Ananda",
      level: "Beginner",
      students: 5600,
      price: "₹299/mo",
      icon: "🧘",
    },
    {
      id: "he4",
      religion: "hindu",
      title: "Hindu Philosophy",
      instructor: "Prof. Nair",
      level: "Intermediate",
      students: 780,
      price: "Free",
      icon: "🕉️",
    },
  ],
  christian: [
    {
      id: "ce1",
      religion: "christian",
      title: "Bible Study Course",
      instructor: "Pastor Thomas",
      level: "All levels",
      students: 2200,
      price: "Free",
      icon: "✝️",
      meetLink: "https://meet.google.com/uvw-mnop-qrs",
    },
    {
      id: "ce2",
      religion: "christian",
      title: "Christian Theology",
      instructor: "Rev. Samuel",
      level: "Advanced",
      students: 430,
      price: "₹299/mo",
      icon: "📖",
    },
    {
      id: "ce3",
      religion: "christian",
      title: "Gospel Music",
      instructor: "Sister Mary",
      level: "Beginner",
      students: 890,
      price: "Free",
      icon: "🎵",
    },
    {
      id: "ce4",
      religion: "christian",
      title: "Church History",
      instructor: "Dr. Philip",
      level: "Intermediate",
      students: 340,
      price: "₹199/mo",
      icon: "🏛️",
    },
  ],
};

// COMMUNITY POSTS
export const COMMUNITY_POSTS = [
  {
    id: "1",
    author: "Priya Kumar",
    avatar: "👩",
    time: "2h ago",
    content:
      "Just had an amazing reading with Pandit Rajesh! My career concerns were addressed perfectly. Highly recommend! 🙏",
    likes: 245,
    comments: 42,
  },
  {
    id: "2",
    author: "Arjun Singh",
    avatar: "👨",
    time: "4h ago",
    content:
      "Learning Vedic astrology has changed my perspective on life. The courses here are excellent quality.",
    likes: 182,
    comments: 28,
  },
  {
    id: "3",
    author: "Anjali Nair",
    avatar: "👱‍♀️",
    time: "6h ago",
    content:
      "The daily prayers have become a part of my routine. Feeling more connected spiritually than ever!",
    likes: 325,
    comments: 67,
  },
];

// DOCTORS DATA
export const DOCTORS = [
  {
    id: "d1",
    name: "Dr. Sarah Ahmed",
    rating: 4.9,
    experience: 10,
    pricePerMin: 35,
    isOnline: true,
    languages: ["English", "Hindi"],
    specialties: ["Psychology", "Counseling"],
    avatar: "👩‍⚕️",
  },
  {
    id: "d2",
    name: "Dr. Amit Patel",
    rating: 4.7,
    experience: 12,
    pricePerMin: 30,
    isOnline: true,
    languages: ["Hindi", "English"],
    specialties: ["General", "Wellness"],
    avatar: "👨‍⚕️",
  },
  {
    id: "d3",
    name: "Dr. Elizabeth George",
    rating: 4.8,
    experience: 18,
    pricePerMin: 50,
    isOnline: false,
    languages: ["English", "Malayalam"],
    specialties: ["Ayurveda", "Therapy"],
    avatar: "👩‍⚕️",
  },
  {
    id: "d4",
    name: "Dr. Mohammed Ali",
    rating: 4.9,
    experience: 15,
    pricePerMin: 40,
    isOnline: true,
    languages: ["English", "Hindi"],
    specialties: ["Ayurveda", "Wellness"],
    avatar: "👨‍⚕️",
  },
  {
    id: "d5",
    name: "Dr. Kavitha Menon",
    rating: 4.6,
    experience: 8,
    pricePerMin: 25,
    isOnline: true,
    languages: ["Malayalam", "English"],
    specialties: ["Nutrition", "Dietetics"],
    avatar: "👩‍⚕️",
  },
];

// PROVIDER MOCK SESSIONS
export const PROVIDER_SESSIONS_UPCOMING = [
  { id: '1', seekerName: 'Rahul Mehta', type: 'Chat', date: '12', month: 'Jun', time: '10:30 AM', duration: '30 min', status: 'Confirmed', amount: 750 },
  { id: '2', seekerName: 'Priya Sharma', type: 'Call', date: '12', month: 'Jun', time: '2:00 PM', duration: '45 min', status: 'Confirmed', amount: 1125 },
  { id: '3', seekerName: 'Arjun Kumar', type: 'Video', date: '13', month: 'Jun', time: '11:00 AM', duration: '60 min', status: 'Pending', amount: 1500 },
];

export const PROVIDER_SESSIONS_COMPLETED = [
  { id: '4', seekerName: 'Meera Nair', type: 'Chat', date: '10', month: 'Jun', time: '9:00 AM', duration: '25 min', status: 'Completed', amount: 625 },
  { id: '5', seekerName: 'Suresh K.', type: 'Call', date: '9', month: 'Jun', time: '4:30 PM', duration: '30 min', status: 'Completed', amount: 900 },
];

export const PROVIDER_SESSIONS_CANCELLED = [
  { id: '6', seekerName: 'Anil P.', type: 'Video', date: '8', month: 'Jun', time: '3:00 PM', duration: '60 min', status: 'Cancelled', reason: 'Seeker cancelled the session' },
];

export const PROVIDER_MESSAGES = [
  { id: '1', seekerName: 'Rahul Mehta', lastMsg: 'Thank you for the guidance!', time: '9:30 AM', unread: 2 },
  { id: '2', seekerName: 'Priya Sharma', lastMsg: 'Can we schedule another session?', time: 'Yesterday', unread: 0 },
  { id: '3', seekerName: 'Arjun Kumar', lastMsg: 'I wanted to ask about my birth chart...', time: 'Mon', unread: 1 },
];

export const PROVIDER_REVIEWS = [
  { id: '1', seekerName: 'Rahul Mehta', rating: 5, text: 'Excellent consultation! Very accurate and helpful guidance.', time: '2 days ago' },
  { id: '2', seekerName: 'Priya Sharma', rating: 5, text: 'Highly recommended. Very professional and insightful.', time: '5 days ago' },
  { id: '3', seekerName: 'Meera Nair', rating: 4, text: 'Good session. Would like to book again soon.', time: '1 week ago' },
];

